/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IForum, IForumInterface } from "../../Vault.sol/IForum";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "score",
        type: "uint256",
      },
    ],
    name: "addContribution",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isModerator",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "updateScores",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IForum__factory {
  static readonly abi = _abi;
  static createInterface(): IForumInterface {
    return new utils.Interface(_abi) as IForumInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IForum {
    return new Contract(address, _abi, signerOrProvider) as IForum;
  }
}
