/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from './common'

export interface ForumInterface extends utils.Interface {
  functions: {
    'baseURI()': FunctionFragment
    'initialized()': FunctionFragment
    'moderatorsCount()': FunctionFragment
    'provideMembership(address[],string[])': FunctionFragment
    'revokeMembership(address[])': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'baseURI'
      | 'initialized'
      | 'moderatorsCount'
      | 'provideMembership'
      | 'revokeMembership'
  ): FunctionFragment

  encodeFunctionData(functionFragment: 'baseURI', values?: undefined): string
  encodeFunctionData(functionFragment: 'initialized', values?: undefined): string
  encodeFunctionData(functionFragment: 'moderatorsCount', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'provideMembership',
    values: [PromiseOrValue<string>[], PromiseOrValue<string>[]]
  ): string
  encodeFunctionData(
    functionFragment: 'revokeMembership',
    values: [PromiseOrValue<string>[]]
  ): string

  decodeFunctionResult(functionFragment: 'baseURI', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'initialized', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'moderatorsCount', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'provideMembership', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'revokeMembership', data: BytesLike): Result

  events: {}
}

export interface Forum extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: ForumInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    baseURI(overrides?: CallOverrides): Promise<[string]>

    initialized(overrides?: CallOverrides): Promise<[boolean]>

    moderatorsCount(overrides?: CallOverrides): Promise<[BigNumber]>

    provideMembership(
      users: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    revokeMembership(
      users: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>
  }

  baseURI(overrides?: CallOverrides): Promise<string>

  initialized(overrides?: CallOverrides): Promise<boolean>

  moderatorsCount(overrides?: CallOverrides): Promise<BigNumber>

  provideMembership(
    users: PromiseOrValue<string>[],
    tokenURIs: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  revokeMembership(
    users: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    baseURI(overrides?: CallOverrides): Promise<string>

    initialized(overrides?: CallOverrides): Promise<boolean>

    moderatorsCount(overrides?: CallOverrides): Promise<BigNumber>

    provideMembership(
      users: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>

    revokeMembership(users: PromiseOrValue<string>[], overrides?: CallOverrides): Promise<void>
  }

  filters: {}

  estimateGas: {
    baseURI(overrides?: CallOverrides): Promise<BigNumber>

    initialized(overrides?: CallOverrides): Promise<BigNumber>

    moderatorsCount(overrides?: CallOverrides): Promise<BigNumber>

    provideMembership(
      users: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    revokeMembership(
      users: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    baseURI(overrides?: CallOverrides): Promise<PopulatedTransaction>

    initialized(overrides?: CallOverrides): Promise<PopulatedTransaction>

    moderatorsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>

    provideMembership(
      users: PromiseOrValue<string>[],
      tokenURIs: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    revokeMembership(
      users: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>
  }
}
