/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionVy from './Auction.vy'
export type { auctionVy }
export type { Lock } from './Lock'
export * as factories from './factories'
export type { Auction } from './Auction.vy/Auction'
export { Auction__factory } from './factories/Auction.vy/Auction__factory'
export { Lock__factory } from './factories/Lock__factory'
